### ISSUE TITLE
The rendering of the tree view items isn't theme aware.

### ISSUE THREAD

**Issue by IEvangelist** [timheuer/GitHubActionsVS#10]
For example, with the **Dark** theme applied this is what it looks like:
![image](https://github.com/timheuer/GitHubActionsVS/assets/7679720/c1dd94ba-551f-461d-89c2-a01b3d3d8d37)

**Comment by timheuer** [comment]
doh! I know why.  WPF doesn't natively support color emoji so my current shim is using a 3rd party control.  And the VSTheme doesn't flow to control heirarchy...just need to set it.

**Comment by timheuer** [comment]
I take that back -- EmojiWPF is hard-coding some colors :-(

**Comment by IEvangelist** [comment]
> I take that back -- EmojiWPF is hard-coding some colors :-(

I think the emoji are fine, but the text is the issue.

**Comment by timheuer** [comment]
@all-contributors add @timheuer for code,docs

**Comment by timheuer** [comment]
Regressed with move to changed datatemplate
